### ISSUE TITLE
Hapaxes function cannot be used anymore?

### ISSUE THREAD

**Issue by eduOS** [alukach/nltk-experiments#1]
```
Hapaxes (least common words):
FreqDist(text1).hepaxes()
```

I tried this but failed saying that `'FreqDist' object has no attribute 'hepaxes'`. Can you tell me the equivalent/alternative function?

**Comment by alukach** [comment]
Hey, sorry for the slow reply.  Unfortunately, I put down the NLTK and haven't worked with it in a long time.  I'd suggest you head over to StackOverflow or try the #NLTK channel on Freenode.

Best of luck!
